name: Extraer rushe.zip

on:
  push:
    paths:
      - 'rushe.zip'
    branches:
      - main

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Unzip rushe.zip
      run: |
        unzip -o rushe.zip -d ./
        rm rushe.zip

    - name: Commit extracted files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Extraído automático de rushe.zip"
        git push
